const N=["チョコオールド","クランチキャラメル","シュガーリング","シュガーツイスト","いちご","チョコ","ホワイト","キャラメル"];
const defaults=N.map(n=>({name:n,price:150,max:50,stock:50}));
let P=JSON.parse(localStorage.getItem("bpos_products")||"null")||defaults.map(x=>({...x}));
let Q=Array(8).fill(0), H=JSON.parse(localStorage.getItem("bpos_history")||"[]");
const money=n=>"¥"+Math.round(n).toLocaleString("ja-JP");
function save(){localStorage.setItem("bpos_products",JSON.stringify(P));localStorage.setItem("bpos_history",JSON.stringify(H))}
function render(){products.innerHTML=P.map((p,i)=>`<div class="product"><h3>${p.name}</h3><div class="price">${money(p.price)}</div><div>在庫：${p.stock}個</div><div class="qty"><button onclick="chg(${i},-1)">−</button><b>${Q[i]}</b><button onclick="chg(${i},1)" ${Q[i]>=p.stock?"disabled":""}>＋</button></div></div>`).join("");total.textContent=money(Q.reduce((s,q,i)=>s+q*P[i].price,0));stock.innerHTML=P.map(p=>`<div class="stockrow"><span>${p.name}</span><span class="stocknum ${p.stock===0?"zero":p.stock<=5?"low":""}">${p.stock}個</span></div>`).join("");settings.innerHTML=P.map((p,i)=>`<div class="setting"><b>${p.name}</b><label>価格<input id="pr${i}" type="number" min="0" value="${p.price}"></label><label>最大<input id="mx${i}" type="number" min="0" max="99" value="${p.max}"></label></div>`).join("");historyBox.innerHTML=H.length?H.slice().reverse().map(h=>`<div class="historyrow"><b>#${String(h.id).padStart(4,"0")}</b>　${h.items.map(x=>x.name+"×"+x.qty).join(" / ")}　${money(h.total)}</div>`).join(""):"履歴なし"}
function chg(i,d){Q[i]=Math.max(0,Math.min(P[i].stock,Q[i]+d));render()}
function saveSettings(){P.forEach((p,i)=>{p.price=Math.max(0,Number(document.getElementById("pr"+i).value)||0);p.max=Math.min(99,Math.max(0,Number(document.getElementById("mx"+i).value)||0));if(p.stock>p.max)p.stock=p.max});save();render();alert("設定を保存しました")}
function makeBarcode(){if(!Q.some(Boolean))return alert("商品を選択してください");const id=(H.at(-1)?.id||0)+1;const items=Q.map((q,i)=>q?{name:N[i],qty:q,price:P[i].price}:null).filter(Boolean),tot=items.reduce((s,x)=>s+x.qty*x.price,0);const code="B05"+String(id).padStart(4,"0")+Q.map(q=>String(q).padStart(2,"0")).join("")+P.map(p=>String(Math.round(p.price)).padStart(4,"0")).join("");H.push({id,items,total:tot});Q.forEach((q,i)=>P[i].stock-=q);save();render();barcodeTitle.textContent=`注文 #${String(id).padStart(4,"0")}　${money(tot)}`;barcodeText.textContent=code;try{JsBarcode("#barcodeCanvas",code,{format:"CODE128",displayValue:true,height:110,margin:18})}catch(e){barcodeCanvas.outerHTML='<p>バーコード生成ライブラリを読み込めませんでした。ネット接続を確認してください。</p>'}download.onclick=()=>{const a=document.createElement("a");a.href=barcodeCanvas.toDataURL("image/png");a.download=`order-${id}.png`;a.click()};modal.classList.remove("hidden");Q=Array(8).fill(0)}
save.onclick=saveSettings;create.onclick=makeBarcode;close.onclick=()=>modal.classList.add("hidden");clear.onclick=()=>{if(confirm("履歴を消去しますか？")){H=[];save();render()}};render();